/**
 * AI Action Proposal Data Model & Helper Methods
 * Path: models/AIActionProposal.js
 * 
 * Represents an autonomous action generated by an AI agent that requires
 * human review, approval, execution tracking, or audit logging.
 */

export const ACTION_PROPOSAL_STATUS = {
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
    EXECUTED: "executed",
    FAILED: "failed",
    CANCELLED: "cancelled",
};

export const RISK_LEVELS = {
    LOW: "low",
    MEDIUM: "medium",
    HIGH: "high",
    CRITICAL: "critical",
};

export class AIActionProposal {
    /**
     * Constructs an AIActionProposal instance
     * @param {Object} data 
     */
    constructor(data = {}) {
        this.id = data.id || null;
        this.ticketId = data.ticketId || data.ticket_id || null;
        this.executionId = data.executionId || data.execution_id || null;
        this.userId = data.userId || data.user_id || null;
        this.orgId = data.orgId || data.org_id || null;

        // Proposal details
        this.agentName = data.agentName || data.agent_name || "SupportOps AI";
        this.actionType = data.actionType || data.action_type || "UNKNOWN";
        this.summary = data.summary || "";
        this.payload = data.payload || {}; // Parameters or code payload to execute

        // Evaluation & Human-in-the-Loop (HITL)
        this.confidenceScore = data.confidenceScore ?? data.confidence_score ?? 0; // 0 - 100
        this.riskLevel = data.riskLevel || data.risk_level || RISK_LEVELS.LOW;
        this.status = data.status || ACTION_PROPOSAL_STATUS.PENDING;

        // Approval metadata
        this.reviewedBy = data.reviewedBy || data.reviewed_by || null;
        this.reviewedAt = data.reviewedAt || data.reviewed_at || null;
        this.rejectionReason = data.rejectionReason || data.rejection_reason || null;

        // Timestamps
        this.createdAt = data.createdAt || data.created_at || new Date().toISOString();
        this.updatedAt = data.updatedAt || data.updated_at || new Date().toISOString();
    }

    /**
     * Helper: Map PostgreSQL database row to AIActionProposal model instance
     * @param {Object} row 
     * @returns {AIActionProposal}
     */
    static fromRow(row) {
        if (!row) return null;
        return new AIActionProposal({
            id: row.id,
            ticketId: row.ticket_id,
            executionId: row.execution_id,
            userId: row.user_id,
            orgId: row.org_id,
            agentName: row.agent_name,
            actionType: row.action_type,
            summary: row.summary,
            payload: typeof row.payload === "string" ? JSON.parse(row.payload) : row.payload,
            confidenceScore: parseFloat(row.confidence_score),
            riskLevel: row.risk_level,
            status: row.status,
            reviewedBy: row.reviewed_by,
            reviewedAt: row.reviewed_at,
            rejectionReason: row.rejection_reason,
            createdAt: row.created_at,
            updatedAt: row.updated_at,
        });
    }

    /**
     * Save a new AI Action Proposal into PostgreSQL
     * @param {Object} pg - Fastify PostgreSQL pool/client
     * @param {Object} proposalData 
     * @returns {Promise<AIActionProposal>}
     */
    static async create(pg, proposalData) {
        const proposal = new AIActionProposal(proposalData);
        const client = await pg.connect();

        try {
            const query = `
          INSERT INTO ai_action_proposals (
            ticket_id, execution_id, user_id, org_id,
            agent_name, action_type, summary, payload,
            confidence_score, risk_level, status
          )
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
          RETURNING *;
        `;

            const values = [
                proposal.ticketId,
                proposal.executionId,
                proposal.userId,
                proposal.orgId,
                proposal.agentName,
                proposal.actionType,
                proposal.summary,
                JSON.stringify(proposal.payload),
                proposal.confidenceScore,
                proposal.riskLevel,
                proposal.status,
            ];

            const res = await client.query(query, values);
            return AIActionProposal.fromRow(res.rows[0]);
        } finally {
            client.release();
        }
    }

    /**
     * Find proposal by ID
     * @param {Object} pg 
     * @param {string|number} id 
     * @returns {Promise<AIActionProposal|null>}
     */
    static async findById(pg, id) {
        const client = await pg.connect();
        try {
            const res = await client.query(
                "SELECT * FROM ai_action_proposals WHERE id = $1",
                [id]
            );
            return res.rows[0] ? AIActionProposal.fromRow(res.rows[0]) : null;
        } finally {
            client.release();
        }
    }

    /**
     * Fetch all pending proposals requiring human approval
     * @param {Object} pg 
     * @param {string|number} [orgId] 
     * @returns {Promise<AIActionProposal[]>}
     */
    static async findPending(pg, orgId = null) {
        const client = await pg.connect();
        try {
            let query = `
          SELECT * FROM ai_action_proposals 
          WHERE status = $1 
        `;
            const params = [ACTION_PROPOSAL_STATUS.PENDING];

            if (orgId) {
                query += ` AND org_id = $2`;
                params.push(orgId);
            }

            query += ` ORDER BY created_at DESC;`;

            const res = await client.query(query, params);
            return res.rows.map((row) => AIActionProposal.fromRow(row));
        } finally {
            client.release();
        }
    }

    /**
     * Approve or reject a proposal
     * @param {Object} pg 
     * @param {string|number} proposalId 
     * @param {Object} reviewData 
     * @param {string} reviewData.status - "approved" or "rejected"
     * @param {string|number} reviewData.reviewerId 
     * @param {string} [reviewData.rejectionReason]
     * @returns {Promise<AIActionProposal>}
     */
    static async updateReview(pg, proposalId, { status, reviewerId, rejectionReason = null }) {
        const client = await pg.connect();
        try {
            const query = `
          UPDATE ai_action_proposals
          SET status = $1,
              reviewed_by = $2,
              reviewed_at = CURRENT_TIMESTAMP,
              rejection_reason = $3,
              updated_at = CURRENT_TIMESTAMP
          WHERE id = $4
          RETURNING *;
        `;

            const res = await client.query(query, [
                status,
                reviewerId,
                rejectionReason,
                proposalId,
            ]);

            if (res.rows.length === 0) {
                throw new Error("ACTION_PROPOSAL_NOT_FOUND");
            }

            return AIActionProposal.fromRow(res.rows[0]);
        } finally {
            client.release();
        }
    }

    /**
     * Update proposal execution status
     * @param {Object} pg 
     * @param {string|number} proposalId 
     * @param {string} status - "executed" or "failed"
     * @returns {Promise<AIActionProposal>}
     */
    static async markExecuted(pg, proposalId, status = ACTION_PROPOSAL_STATUS.EXECUTED) {
        const client = await pg.connect();
        try {
            const res = await client.query(
                `UPDATE ai_action_proposals 
           SET status = $1, updated_at = CURRENT_TIMESTAMP 
           WHERE id = $2 
           RETURNING *;`,
                [status, proposalId]
            );
            return AIActionProposal.fromRow(res.rows[0]);
        } finally {
            client.release();
        }
    }
}